### ISSUE TITLE
Default custom highlighting CSS using ".from" is broken

### ISSUE THREAD

**Issue by jack-d-watson** [paul-lrr/nifty-chat-monitor#17]
".from" is no longer the class for the username. Any references to ".from" should be updated to ".chat-author__display-name"

I would fix it now but I can't get to a computer that could test it all properly and I don't want to forget.

-Jack

**Comment by paul-lrr** [comment]
this is actually already fixed on the new-twitch branch, which I have been testing. Should be merging it into the master later on today

**Comment by paul-lrr** [comment]
should be fixed now!
