### ISSUE TITLE
Subscription Notification Chat Message Display

### ISSUE THREAD

**Issue by MarkDumontier** [paul-lrr/nifty-chat-monitor#2]
The chat message accompanying a subscription displays with a light background and white text, making it difficult to read.
Example:
https://imgur.com/a/jWC9Q

**Comment by jack-d-watson** [comment]
I saw this as well today. It appears that the system-msg class is setting the background color to white for the official notifier messages like "X just subscribed with a $x sub". We probably just need to override it.

**Comment by paul-lrr** [comment]
should be fixed now. I have overridden `.special-message` and `.system-msg` with `background-color:inherit` (to maintain zebra striping) If you *do* want to highlight sub messages, you can use the message keyword hook to search for lines with "just subscribed"
