### ISSUE TITLE
'@Username' purple background

### ISSUE THREAD

**Issue by jack-d-watson** [paul-lrr/nifty-chat-monitor#20]
I noticed some new functionality we should probably handle somehow.

![image](https://user-images.githubusercontent.com/1895304/39896188-1e85a868-547b-11e8-9146-e55a49530007.png)

I think it's using  .mention-fragment 
At the very least we should increase the size of the box to properly encapsulate the username.

**Comment by jack-d-watson** [comment]
Apparently it looks like this now? 
![image](https://user-images.githubusercontent.com/1895304/39947145-d1fc33d0-553e-11e8-8912-9c45f1971bd5.png)
Twitch you're great and all but please stop changing this chat every time I open it.

**Comment by Glodenox** [comment]
Yeah, I just noticed it as well. I'm not sure whether it is useful in any way to display mentions with another background though. Perhaps it could be considered to just remove the background?
